"""OpsPilot — agentic request triage & remediation. Streamlit entrypoint."""
from __future__ import annotations

import json
import time

import pandas as pd
import streamlit as st

import agent
import config
import db
import gemini_client
import seed_data
import ui
from models import (AgentRun, Classification, IncomingRequest, PlannedStep,
                    new_request_id, now_iso)

st.set_page_config(page_title="OpsPilot — Agentic Request Triage", page_icon="🛰️",
                   layout="wide")
ui.inject_css()

# idempotent: guarantees the schema exists even if the .db file was removed
# while the app was running
db.init_db()
if "initialized" not in st.session_state:
    seed_data.write_sample_csv()
    st.session_state.initialized = True
    st.session_state.last_run = None

# ---------------------------------------------------------------- sidebar

with st.sidebar:
    st.markdown("### ⚙️ Agent controls")
    autonomy_mode = st.radio("Autonomy mode", config.AUTONOMY_MODES,
                             help="How much the agent may do without a human.")
    critic_enabled = st.toggle("🪞 Critic agent (draft compliance review)",
                               value=config.CRITIC_ENABLED_DEFAULT)
    config.CONFIDENCE_THRESHOLD = st.slider(
        "Confidence threshold for auto-processing", 0.5, 0.9, 0.70, 0.05)
    st.divider()
    api_ok = gemini_client.api_available()
    if api_ok:
        st.success("Gemini API connected", icon="✅")
    else:
        st.error("No GEMINI_API_KEY — offline fallback mode (keyword triage + "
                 "template drafts). Add your key to `.env`.", icon="🔌")
    with st.expander("About the agent"):
        st.markdown(
            "For every request, OpsPilot **recalls sender history** (memory), makes "
            "**one fused Gemini call** that classifies the request AND composes a "
            "remediation plan of tool calls with per-step justifications, then a "
            "deterministic **policy guardrail** repairs the plan to the playbook "
            "(mandatory steps enforced, forbidden stripped). Low-confidence cases "
            "gate to **human review**. An executor runs the tools, and a **critic "
            "agent** compliance-reviews customer-facing drafts before they ship. "
            "Every reasoning artifact is persisted to a glass-box audit trail.")

ui.hero(api_ok, autonomy_mode, critic_enabled)

# ---------------------------------------------------------------- trace rendering


def render_reasoning(cls: Classification, memory_note: str, memory_impact: str):
    chips = " &nbsp; ".join([
        ui.type_chip(cls.request_type),
        ui.urgency_pill(cls.urgency),
        ui.pill(ui.SOURCE_LABEL.get(cls.source, cls.source), "neutral", dot=False),
        ui.pill(f"sentiment: {cls.sentiment}", "neutral", dot=False),
    ])
    body = chips + ui.confidence_meter(cls.confidence, config.CONFIDENCE_THRESHOLD)
    body += f'<div class="op-rationale"><b>Rationale.</b> {cls.rationale}</div>'
    if memory_note:
        body += f'<div class="op-note mem">💾 <b>Memory.</b> {memory_note}</div>'
    if memory_impact and memory_impact.lower() not in ("none", "human decision", ""):
        body += (f'<div class="op-note">🔁 <b>Memory changed the plan.</b> '
                 f'{memory_impact}</div>')
    ui.card("🧠 Agent reasoning", body)


def render_plan(plan: list[PlannedStep], flags: list[str],
                title: str = "📋 Remediation plan"):
    rows = [{"key": s.key(), "reason": s.reason, "origin": s.origin} for s in plan]
    ui.card(title, ui.plan_table(rows))
    if flags:
        for f in flags:
            ui.flag(f"Guardrail: {f}")
    else:
        ui.flag("Agent's plan was fully policy-compliant — no repairs needed",
                ok=True)


def render_results(results, critic):
    st.markdown('<div class="op-card-title" style="font-size:0.74rem;font-weight:700;'
                'text-transform:uppercase;letter-spacing:0.08em;color:#898781;'
                'margin:6px 0 10px 0">⚙️ Execution timeline</div>',
                unsafe_allow_html=True)
    icon = {"SUCCESS": "✅", "FAILED": "❌", "SKIPPED": "⏭️"}
    for i, r in enumerate(results):
        artifact = r.artifact if isinstance(r.artifact, dict) else {}
        with st.expander(f"{icon.get(r.status, '•')} {i + 1} · {r.tool} — "
                         f"{r.status} · {r.executed_at}",
                         expanded=(r.tool == "draft_reply")):
            text = artifact.get("draft_text") or artifact.get("text")
            if text:
                meta = []
                if artifact.get("generated_by"):
                    meta.append(f"generated by {artifact['generated_by']}")
                if artifact.get("revised_by_critic"):
                    meta.append("✍️ revised by critic")
                ui.draft_block(text, " · ".join(meta))
                rest = {k: v for k, v in artifact.items()
                        if k not in ("draft_text", "text")}
                if rest:
                    st.json(rest, expanded=False)
            else:
                st.json(artifact)
    if critic:
        if not critic.get("available", True):
            ui.card("🪞 Critic verdict",
                    '<span style="color:#52514e">Critic unavailable — draft '
                    'shipped unreviewed.</span>')
        elif critic["approved"]:
            ui.card("🪞 Critic verdict",
                    ui.pill("draft approved", "good") +
                    '<span style="color:#52514e;font-size:0.88rem"> &nbsp;All '
                    'compliance checks passed.</span>')
        else:
            issues = "".join(f'<li>{i}</li>' for i in critic["issues"])
            ui.card("🪞 Critic verdict",
                    ui.pill("draft rejected & revised", "warning") +
                    f'<ul style="margin:10px 0 0 0;color:#52514e;'
                    f'font-size:0.88rem">{issues}</ul>')
            col1, col2 = st.columns(2)
            with col1:
                ui.draft_block(critic["original_text"], "original draft")
            with col2:
                ui.draft_block(critic["revised_text"], "revised draft (shipped)")


def render_run(run: AgentRun):
    render_reasoning(run.classification, run.memory_note, run.memory_impact)
    render_plan(run.final_plan, run.guardrail_flags)
    if str(run.final_status).replace("CaseStatus.", "") == "PENDING_REVIEW":
        st.markdown(
            f'<div class="op-card">{ui.status_pill("PENDING_REVIEW")}'
            f'<span style="color:#52514e;font-size:0.9rem"> &nbsp;Confidence '
            f'{run.classification.confidence:.2f} is below the threshold '
            f'({config.CONFIDENCE_THRESHOLD:.2f}) or approval is required — case '
            f'<b>{run.request.id}</b> is waiting in the <b>Human Review</b> tab. '
            f'Nothing was executed.</span></div>', unsafe_allow_html=True)
        return
    render_results(run.results, run.critic)
    follow_up = db.get_case(run.request.id).get("follow_up_at")
    tail = (f'<span style="color:#898781;font-size:0.85rem"> &nbsp;⏰ follow-up / '
            f'SLA: <code>{follow_up}</code></span>' if follow_up else "")
    st.markdown(f'<div class="op-card"><div class="op-card-title">Final status'
                f'</div>{ui.status_pill(run.final_status)}{tail}</div>',
                unsafe_allow_html=True)


def run_agent_with_status(req: IncomingRequest, **kwargs) -> AgentRun:
    with st.status(f"🛰️ Agent processing {req.id}…", expanded=True) as status:
        st.write("💾 Recalling sender memory…")
        st.write("🧠 Planning (classification + remediation plan)…")
        run = agent.process_request(req, autonomy_mode=autonomy_mode,
                                    critic_enabled=critic_enabled, **kwargs)
        st.write("🛡️ Plan validated against playbook policy")
        if run.results:
            st.write(f"⚙️ Executed {len(run.results)} steps")
        if run.critic:
            st.write("🪞 Critic review complete")
        final = str(run.final_status).replace("CaseStatus.", "").replace("_", " ")
        status.update(label=f"Agent run complete — {final}",
                      state="complete", expanded=False)
    return run


# ---------------------------------------------------------------- tabs

tab_process, tab_review, tab_batch, tab_dash = st.tabs(
    ["📥  Process Request", "👤  Human Review", "📦  Batch", "📊  Dashboard & Audit"])

with tab_process:
    left, right = st.columns([5, 7], gap="large")
    with left:
        st.markdown("#### Incoming request")
        mode = st.radio("Source", ["Simulated inbox", "Manual form"],
                        horizontal=True, label_visibility="collapsed")
        if mode == "Manual form":
            with st.form("manual_form"):
                sender = st.text_input("Sender email",
                                       placeholder="customer@example.com")
                subject = st.text_input("Subject")
                body = st.text_area("Message body", height=160)
                submitted = st.form_submit_button("🛰️ Run Agent", type="primary",
                                                  width="stretch")
            if submitted:
                if not body.strip():
                    st.warning("Message body is empty — nothing to process.")
                else:
                    req = IncomingRequest(
                        id=new_request_id(), channel="form",
                        sender=sender.strip() or "unknown@example.com",
                        subject=subject.strip() or "(no subject)",
                        body=body.strip(), received_at=now_iso())
                    st.session_state.last_run = run_agent_with_status(req)
        else:
            options = {f"{i + 1}. {s['subject']} — {s['sender']}": s
                       for i, s in enumerate(seed_data.SAMPLE_INBOX)}
            choice = st.selectbox("Pick a message from the inbox", list(options))
            sample = options[choice]
            st.text_area("Message preview", sample["body"], height=150,
                         disabled=True)
            if st.button("🛰️ Run Agent", type="primary",
                         width="stretch"):
                req = IncomingRequest(id=new_request_id(), channel="inbox",
                                      sender=sample["sender"],
                                      subject=sample["subject"],
                                      body=sample["body"], received_at=now_iso())
                st.session_state.last_run = run_agent_with_status(req)
    with right:
        if st.session_state.last_run:
            st.markdown(f"#### Agent trace — `{st.session_state.last_run.request.id}`")
            render_run(st.session_state.last_run)
        else:
            st.markdown(
                '<div class="op-card" style="text-align:center;padding:60px 20px;'
                'color:#898781">Process a request to see the agent\'s full '
                'reasoning trace here —<br/>classification, self-composed plan, '
                'guardrail checks, execution artifacts and critic verdict.</div>',
                unsafe_allow_html=True)

with tab_review:
    st.markdown("#### 👤 Human review queue")
    pending = db.get_cases("PENDING_REVIEW")
    if pending.empty:
        st.markdown('<div class="op-card" style="color:#898781">No cases awaiting '
                    'review.</div>', unsafe_allow_html=True)
    else:
        ids = pending["id"].tolist()
        case_id = st.selectbox(
            "Pending case", ids,
            format_func=lambda i: f"{i} — "
            f"{pending.set_index('id').loc[i, 'subject']}")
        case = db.get_case(case_id)
        st.text_area("Message", case["body"], height=110, disabled=True,
                     key=f"body_{case_id}")
        cls = Classification(
            request_type=case["request_type"], urgency=case["urgency"],
            confidence=case["confidence"], rationale=case["rationale"],
            sentiment=case["sentiment"],
            suggested_department=case["department"], source=case["class_source"])
        render_reasoning(cls, case["memory_note"], "")
        proposed = db.get_plan(case_id, "proposed")
        render_plan(proposed, json.loads(case["guardrail_flags"] or "[]"),
                    title="📋 Agent's proposed plan")

        st.markdown("##### Operator decision")
        col1, col2 = st.columns(2)
        with col1:
            new_type = st.selectbox("Request type", config.REQUEST_TYPES,
                                    index=config.REQUEST_TYPES.index(
                                        case["request_type"]))
        with col2:
            new_urgency = st.selectbox("Urgency", config.URGENCY_LEVELS,
                                       index=config.URGENCY_LEVELS.index(
                                           case["urgency"]))
        keep = []
        if new_type == case["request_type"] and proposed:
            st.caption("Keep / drop the agent's proposed steps (mandatory steps are "
                       "re-enforced by the guardrail either way):")
            for i, step in enumerate(proposed):
                if st.checkbox(f"`{step.key()}` — {step.reason}", value=True,
                               key=f"keep_{case_id}_{i}"):
                    keep.append(step)
        if st.button("✅ Approve & Execute", type="primary"):
            human_cls = Classification(
                request_type=new_type, urgency=new_urgency, confidence=1.0,
                rationale=f"Human operator confirmed as {new_type}/{new_urgency} "
                          f"(AI suggested {case['request_type']}/{case['urgency']} "
                          f"at {case['confidence']:.2f}).",
                sentiment=case["sentiment"],
                suggested_department=case["department"], source="human_override")
            human_plan = ([PlannedStep(tool=s.tool, reason=s.reason, params=s.params,
                                       origin="human") for s in keep]
                          if keep else None)
            req = IncomingRequest(id=case["id"], channel=case["channel"],
                                  sender=case["sender"], subject=case["subject"],
                                  body=case["body"], received_at=case["received_at"])
            st.session_state.last_run = run_agent_with_status(
                req, human_cls=human_cls, human_plan=human_plan)
            st.rerun()

    st.markdown("#### ⛔ Held for human (urgent cases)")
    held = db.get_cases("HELD_FOR_HUMAN")
    if held.empty:
        st.markdown('<div class="op-card" style="color:#898781">No urgent cases on '
                    'hold.</div>', unsafe_allow_html=True)
    else:
        for _, row in held.iterrows():
            col1, col2 = st.columns([4, 1])
            with col1:
                st.markdown(
                    f'<div class="op-card" style="margin-bottom:8px">'
                    f'<b>{row["id"]}</b> — {row["subject"]} &nbsp; '
                    f'{ui.urgency_pill(row["urgency"])} '
                    f'<span style="color:#898781;font-size:0.85rem">'
                    f'{row["sender"]}</span></div>', unsafe_allow_html=True)
            with col2:
                if st.button("Mark handled → Resolve", key=f"resolve_{row['id']}"):
                    db.update_case(row["id"], status="RESOLVED")
                    st.rerun()

    if st.session_state.last_run and st.session_state.last_run.results:
        last = st.session_state.last_run
        if last.classification.source == "human_override":
            st.markdown(f"#### Agent trace — `{last.request.id}` (human-approved)")
            render_run(last)

with tab_batch:
    st.markdown("#### 📦 Batch processing")
    st.caption(f"Throttled to {config.BATCH_THROTTLE_SECONDS:.0f}s between requests "
               f"to respect the Gemini free-tier rate limit.")
    uploaded = st.file_uploader("Upload CSV (columns: sender, subject, body)",
                                type="csv")
    use_sample = st.button("Load sample batch (10 requests)")
    batch_df = None
    if uploaded is not None:
        try:
            batch_df = pd.read_csv(uploaded)
        except Exception as e:  # noqa: BLE001
            st.error(f"Could not read CSV: {e}")
    elif use_sample:
        batch_df = pd.read_csv(seed_data.CSV_PATH)
    if batch_df is not None:
        missing = {"sender", "subject", "body"} - set(batch_df.columns)
        if missing:
            st.error(f"CSV is missing required columns: {sorted(missing)}")
        else:
            st.session_state.batch_df = batch_df
    if "batch_df" in st.session_state:
        st.dataframe(st.session_state.batch_df, width="stretch", height=200)
        if st.button("⚙️ Process batch", type="primary"):
            rows = st.session_state.batch_df.to_dict("records")
            progress = st.progress(0.0, text="Starting batch…")
            summary = []
            for i, row in enumerate(rows):
                req = IncomingRequest(id=new_request_id(), channel="batch",
                                      sender=str(row["sender"]),
                                      subject=str(row["subject"]),
                                      body=str(row["body"]), received_at=now_iso())
                progress.progress((i + 0.5) / len(rows),
                                  text=f"Processing {i + 1}/{len(rows)}: "
                                       f"{req.subject[:50]}")
                run = agent.process_request(req, autonomy_mode=autonomy_mode,
                                            critic_enabled=critic_enabled)
                summary.append({
                    "id": req.id, "subject": req.subject[:50],
                    "type": run.classification.request_type,
                    "urgency": run.classification.urgency,
                    "confidence": round(run.classification.confidence, 2),
                    "status": str(run.final_status).replace("CaseStatus.", ""),
                    "flags": "; ".join(run.guardrail_flags) or "—"})
                progress.progress((i + 1) / len(rows))
                if gemini_client.api_available() and i < len(rows) - 1:
                    time.sleep(config.BATCH_THROTTLE_SECONDS)
            progress.progress(1.0, text="Batch complete")
            st.success(f"Processed {len(summary)} requests.")
            st.dataframe(pd.DataFrame(summary), width="stretch")

with tab_dash:
    stats = db.get_dashboard_stats()
    if stats["total"] == 0:
        st.markdown('<div class="op-card" style="text-align:center;padding:60px;'
                    'color:#898781">No cases processed yet — run a request from '
                    'the Process tab.</div>', unsafe_allow_html=True)
    else:
        cols = st.columns(6)
        ui.stat_tile(cols[0], stats["total"], "Total cases")
        ui.stat_tile(cols[1], stats["resolved"], "Auto-resolved")
        ui.stat_tile(cols[2], stats["pending_review"], "Pending review")
        ui.stat_tile(cols[3], stats["held_for_human"], "Held for human")
        ui.stat_tile(cols[4], f"{stats['avg_confidence']:.2f}", "Avg confidence")
        ui.stat_tile(cols[5], f"{stats['pct_repaired']:.0f}%", "Plans repaired")
        st.write("")

        c1, c2, c3 = st.columns(3)
        with c1:
            st.markdown("###### Volume by request type")
            st.altair_chart(ui.volume_by_type_chart(stats["by_type"]),
                            width="stretch")
        with c2:
            st.markdown("###### Status distribution")
            st.altair_chart(ui.status_chart(stats["by_status"]),
                            width="stretch")
        with c3:
            st.markdown("###### Urgency mix")
            st.altair_chart(ui.urgency_chart(stats["by_urgency"]),
                            width="stretch")

        st.markdown("##### Case log")
        cases = db.get_cases()
        st.dataframe(
            cases[["id", "received_at", "sender", "subject", "request_type",
                   "urgency", "confidence", "class_source", "status",
                   "follow_up_at"]],
            width="stretch", height=260)

        st.markdown("##### 🔍 Audit trail drill-down")
        audit_id = st.selectbox("Case", cases["id"].tolist(),
                                format_func=lambda i: f"{i} — "
                                f"{cases.set_index('id').loc[i, 'subject']}")
        case = db.get_case(audit_id)
        cls = Classification(
            request_type=case["request_type"], urgency=case["urgency"],
            confidence=case["confidence"], rationale=case["rationale"],
            sentiment=case["sentiment"],
            suggested_department=case["department"], source=case["class_source"])
        render_reasoning(cls, case["memory_note"], "")
        final_plan = db.get_plan(audit_id, "final")
        if final_plan:
            render_plan(final_plan, json.loads(case["guardrail_flags"] or "[]"),
                        title="📋 Executed plan")
        audit = db.get_audit(audit_id)
        if audit.empty:
            st.markdown('<div class="op-card" style="color:#898781">No steps '
                        'executed yet (case pending review).</div>',
                        unsafe_allow_html=True)
        else:
            for _, row in audit.iterrows():
                with st.expander(f"{row['tool']} — {row['status']} · "
                                 f"{row['executed_at']}"):
                    st.json(json.loads(row["artifact"]))
        st.markdown(f'<div class="op-card"><div class="op-card-title">Status</div>'
                    f'{ui.status_pill(case["status"])}</div>',
                    unsafe_allow_html=True)
